language: node_js
node_js:
  - "stable"
sudo: required
before_script:
  - npm install jest
script:
  - npm test
branch:
  only:
    - master
services:
  - mongodb
env:
  - MONGOLAB_URI="mongodb://localhost/data-modeling"
notifications:
  email:
    - false
